/**
 * Terminus credential vault schema (CON-50).
 *
 * One unified table holds every upstream credential — platform and BYOK are the
 * same entity, distinguished by `owner`; routing/authorization (not table
 * identity) decides who may use which key (the Helicone `provider_keys` model).
 * Secrets are AES-256-GCM encrypted at rest (`secret_encrypted`), bound to the
 * owner via AAD; they are decrypted only in-isolate, never cached in KV.
 *
 * Accessed exclusively through Drizzle (parameterized queries — no hand-rolled
 * SQL). Migrations are generated by `drizzle-kit generate` into `./migrations`.
 */
import { sql } from "drizzle-orm";
import { check, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

/** Who owns a credential. `platform` = Terminus's own pooled accounts; `tenant` = BYOK. */
export type CredentialOwnerType = "platform" | "tenant";

/** How `secret_encrypted` is interpreted once decrypted. */
export type StoredCredentialMode = "api_key" | "codex-oauth";

export const providerCredentials = sqliteTable(
  "provider_credentials",
  {
    id: text("id").primaryKey(),
    /** `platform` | `tenant`. Single-tenant rollout uses `platform` only. */
    ownerType: text("owner_type").$type<CredentialOwnerType>().notNull().default("platform"),
    /** Tenant id for BYOK; empty for platform. Also the AES-GCM AAD. */
    ownerId: text("owner_id").notNull().default(""),
    /** models.dev provider id, or `codex`. */
    provider: text("provider").notNull(),
    /** `api_key`: secret is the raw key. `codex-oauth`: secret is JSON of the OAuth components. */
    credentialMode: text("credential_mode")
      .$type<StoredCredentialMode>()
      .notNull()
      .default("api_key"),
    /** AES-256-GCM(base64) of the secret (key string, or codex `{refresh,access,account_id}` JSON). */
    secretEncrypted: text("secret_encrypted").notNull(),
    /** OAuth access-token expiry (epoch ms); plaintext so the cron finds near-expiry rows. */
    expiresAt: integer("expires_at"),
    /** Whether to advertise + serve this credential. */
    enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
    /** Provider-specific JSON (baseURL/region overrides). */
    config: text("config"),
    /** Disambiguates multiple credentials for one (owner, provider) — a rotation/LB pool (CON-71). */
    label: text("label").notNull().default("default"),
    /** Routing priority tier; higher = preferred (selected first). */
    priority: integer("priority").notNull().default(0),
    /** Weighted-random share within a priority tier; treated as >= 1. */
    weight: integer("weight").notNull().default(1),
    /** Epoch ms; while now < cooldown_until_ms the row is skipped (rate-limit/health backoff). */
    cooldownUntilMs: integer("cooldown_until_ms"),
    /** Consecutive upstream failures; reset to 0 on success — drives escalating cooldown. */
    failureCount: integer("failure_count").notNull().default(0),
    createdAt: integer("created_at").notNull(),
    updatedAt: integer("updated_at").notNull(),
  },
  (table) => [
    // Pool key (CON-71): multiple credentials per (owner, provider), disambiguated by label.
    uniqueIndex("provider_credentials_owner_provider_label").on(
      table.ownerType,
      table.ownerId,
      table.provider,
      table.label
    ),
    // Owner isolation: a non-platform (tenant) row must carry a non-empty owner_id,
    // so different tenants can't collapse into the same (owner_type,'',provider) bucket.
    check(
      "provider_credentials_tenant_owner_id",
      sql`${table.ownerType} = 'platform' OR ${table.ownerId} <> ''`
    ),
  ]
);

export type ProviderCredentialRow = typeof providerCredentials.$inferSelect;
export type NewProviderCredentialRow = typeof providerCredentials.$inferInsert;

/**
 * Guardrail policy (CON-71 L2) — a Helicone-style versioned config, owner-scoped,
 * mirroring `provider_credentials`. A `policy` names an owner's policy (v1: one
 * `platform-default`); each `policy_version` carries a validated JSON guardrail blob
 * (`policy/blob.ts`). The active version is the one with `is_active = 1` (partial
 * unique → exactly one per policy); rollback flips `is_active` to an older version.
 * There is no routing here — the blob only gates + clamps, never reroutes a model.
 */
export const policies = sqliteTable(
  "policies",
  {
    id: text("id").primaryKey(),
    /** `platform` | `tenant`. Single-tenant rollout uses `platform` only. */
    ownerType: text("owner_type").$type<CredentialOwnerType>().notNull().default("platform"),
    /** Tenant id for per-identity policies; empty for platform. */
    ownerId: text("owner_id").notNull().default(""),
    /** Human-readable policy name, e.g. `platform-default`. */
    name: text("name").notNull(),
    /** Whether the policy is live (a disabled policy is ignored at request time). */
    enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
    createdAt: integer("created_at").notNull(),
    updatedAt: integer("updated_at").notNull(),
  },
  (table) => [
    uniqueIndex("policies_owner_name").on(table.ownerType, table.ownerId, table.name),
    // Owner isolation — mirrors provider_credentials.
    check(
      "policies_tenant_owner_id",
      sql`${table.ownerType} = 'platform' OR ${table.ownerId} <> ''`
    ),
  ]
);

export const policyVersions = sqliteTable(
  "policy_versions",
  {
    id: text("id").primaryKey(),
    /** Logical reference to `policies.id` (no FK — D1 keeps PRAGMA foreign_keys off). */
    policyId: text("policy_id").notNull(),
    /** Monotonic per policy (max(version)+1 at write). */
    version: integer("version").notNull(),
    /** The validated JSON guardrail blob (plaintext — not a secret). */
    config: text("config").notNull(),
    /** Exactly one active version per policy (partial unique index below). */
    isActive: integer("is_active", { mode: "boolean" }).notNull().default(false),
    createdAt: integer("created_at").notNull(),
  },
  (table) => [
    uniqueIndex("policy_versions_policy_version").on(table.policyId, table.version),
    // Exactly one active version per policy.
    uniqueIndex("policy_versions_active")
      .on(table.policyId)
      .where(sql`${table.isActive} = 1`),
  ]
);

export type PolicyRow = typeof policies.$inferSelect;
export type NewPolicyRow = typeof policies.$inferInsert;
export type PolicyVersionRow = typeof policyVersions.$inferSelect;
export type NewPolicyVersionRow = typeof policyVersions.$inferInsert;

/**
 * Broadcast destinations (CON-73) — the runtime-configurable fan-out registry,
 * owner-scoped exactly like `provider_credentials`. Each row is one destination:
 * a `type` discriminator (`otlp`/`posthog`/`webhook`/…), a non-secret `config` JSON
 * blob (endpoint/host/headers/filters), and an AES-256-GCM-encrypted `secret`
 * (the auth material — api key / Basic / Bearer / HMAC key / S3 keys), bound to the
 * owner via AAD just like the vault. No secret ever lives in `config`. Adding,
 * toggling, sampling, and re-credentialling a destination is a row write — no
 * redeploy. The dispatcher reads the enabled set per call (off the response path).
 */
export const broadcastDestinations = sqliteTable(
  "broadcast_destinations",
  {
    id: text("id").primaryKey(),
    /** `platform` | `tenant`. Single-tenant rollout uses `platform` only. */
    ownerType: text("owner_type").$type<CredentialOwnerType>().notNull().default("platform"),
    /** Tenant id for per-tenant destinations; empty for platform. Also the AES-GCM AAD. */
    ownerId: text("owner_id").notNull().default(""),
    /** Adapter discriminator: `otlp` | `posthog` | `webhook` | … */
    type: text("type").notNull(),
    /** Whether to fan out to this destination. */
    enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
    /** Per-trace sampling rate in [0,1]; 1 = always, 0 = never. */
    samplingRate: real("sampling_rate").notNull().default(1),
    /** Non-secret per-destination config JSON (endpoint/host/region, non-secret headers, filters). */
    config: text("config").notNull(),
    /** AES-256-GCM(base64) of the auth-material JSON blob (never any secret in `config`). */
    secretEncrypted: text("secret_encrypted").notNull(),
    /** Disambiguates multiple destinations of one type for an owner (e.g. two OTLP collectors). */
    label: text("label").notNull().default("default"),
    createdAt: integer("created_at").notNull(),
    updatedAt: integer("updated_at").notNull(),
  },
  (table) => [
    // One destination per (owner, type, label); a second of the same type needs a distinct label.
    uniqueIndex("broadcast_destinations_owner_type_label").on(
      table.ownerType,
      table.ownerId,
      table.type,
      table.label
    ),
    // Owner isolation — mirrors provider_credentials.
    check(
      "broadcast_destinations_tenant_owner_id",
      sql`${table.ownerType} = 'platform' OR ${table.ownerId} <> ''`
    ),
  ]
);

export type BroadcastDestinationRow = typeof broadcastDestinations.$inferSelect;
export type NewBroadcastDestinationRow = typeof broadcastDestinations.$inferInsert;
