/**
 * Terminus credential vault schema (CON-50).
 *
 * One unified table holds every upstream credential — platform and BYOK are the
 * same entity, distinguished by `owner`; routing/authorization (not table
 * identity) decides who may use which key (the Helicone `provider_keys` model).
 * Secrets are AES-256-GCM encrypted at rest (`secret_encrypted`), bound to the
 * owner via AAD; they are decrypted only in-isolate, never cached in KV.
 *
 * Accessed exclusively through Drizzle (parameterized queries — no hand-rolled
 * SQL). Migrations are generated by `drizzle-kit generate` into `./migrations`.
 */
import { sql } from "drizzle-orm";
import { check, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

/** Who owns a credential. `platform` = Terminus's own pooled accounts; `tenant` = BYOK. */
export type CredentialOwnerType = "platform" | "tenant";

/** How `secret_encrypted` is interpreted once decrypted. */
export type StoredCredentialMode = "api_key" | "codex-oauth";

export const providerCredentials = sqliteTable(
  "provider_credentials",
  {
    id: text("id").primaryKey(),
    /** `platform` | `tenant`. Single-tenant rollout uses `platform` only. */
    ownerType: text("owner_type").$type<CredentialOwnerType>().notNull().default("platform"),
    /** Tenant id for BYOK; empty for platform. Also the AES-GCM AAD. */
    ownerId: text("owner_id").notNull().default(""),
    /** models.dev provider id, or `codex`. */
    provider: text("provider").notNull(),
    /** `api_key`: secret is the raw key. `codex-oauth`: secret is JSON of the OAuth components. */
    credentialMode: text("credential_mode")
      .$type<StoredCredentialMode>()
      .notNull()
      .default("api_key"),
    /** AES-256-GCM(base64) of the secret (key string, or codex `{refresh,access,account_id}` JSON). */
    secretEncrypted: text("secret_encrypted").notNull(),
    /** OAuth access-token expiry (epoch ms); plaintext so the cron finds near-expiry rows. */
    expiresAt: integer("expires_at"),
    /** Whether to advertise + serve this credential. */
    enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
    /** Provider-specific JSON (baseURL/region overrides). */
    config: text("config"),
    createdAt: integer("created_at").notNull(),
    updatedAt: integer("updated_at").notNull(),
  },
  (table) => [
    uniqueIndex("provider_credentials_owner_provider").on(
      table.ownerType,
      table.ownerId,
      table.provider
    ),
    // Owner isolation: a non-platform (tenant) row must carry a non-empty owner_id,
    // so different tenants can't collapse into the same (owner_type,'',provider) bucket.
    check(
      "provider_credentials_tenant_owner_id",
      sql`${table.ownerType} = 'platform' OR ${table.ownerId} <> ''`
    ),
  ]
);

export type ProviderCredentialRow = typeof providerCredentials.$inferSelect;
export type NewProviderCredentialRow = typeof providerCredentials.$inferInsert;
