# =============================================================================
# Cloudflare D1 Database
# =============================================================================

resource "cloudflare_d1_database" "main" {
  account_id = var.cloudflare_account_id
  name       = "open-inspect-${local.name_suffix}"

  read_replication = {
    mode = "disabled"
  }
}

resource "null_resource" "d1_migrations" {
  depends_on = [cloudflare_d1_database.main]

  triggers = {
    database_id = cloudflare_d1_database.main.id
    migrations_sha = sha256(join(",", [
      for f in sort(fileset("${var.project_root}/terraform/d1/migrations", "*.sql")) :
      filesha256("${var.project_root}/terraform/d1/migrations/${f}")
    ]))
  }

  provisioner "local-exec" {
    command     = "bash scripts/d1-migrate.sh ${cloudflare_d1_database.main.name} terraform/d1/migrations"
    working_dir = var.project_root

    environment = {
      CLOUDFLARE_ACCOUNT_ID = var.cloudflare_account_id
      CLOUDFLARE_API_TOKEN  = var.cloudflare_api_token
    }
  }
}

# =============================================================================
# Terminus credential-vault D1 (CON-50) — separate, self-contained database.
# Migrations are generated by drizzle-kit into services/terminus/migrations.
# =============================================================================

resource "cloudflare_d1_database" "terminus" {
  count      = var.enable_terminus ? 1 : 0
  account_id = var.cloudflare_account_id
  name       = "open-inspect-terminus-${local.name_suffix}"

  read_replication = {
    mode = "disabled"
  }
}

resource "null_resource" "terminus_d1_migrations" {
  count      = var.enable_terminus ? 1 : 0
  depends_on = [cloudflare_d1_database.terminus]

  triggers = {
    database_id = cloudflare_d1_database.terminus[0].id
    migrations_sha = sha256(join(",", [
      for f in sort(fileset("${var.project_root}/services/terminus/migrations", "*.sql")) :
      filesha256("${var.project_root}/services/terminus/migrations/${f}")
    ]))
  }

  provisioner "local-exec" {
    command     = "bash scripts/d1-migrate.sh ${cloudflare_d1_database.terminus[0].name} services/terminus/migrations"
    working_dir = var.project_root

    environment = {
      CLOUDFLARE_ACCOUNT_ID = var.cloudflare_account_id
      CLOUDFLARE_API_TOKEN  = var.cloudflare_api_token
    }
  }
}
